### ISSUE TITLE
Group project endpointi

### ISSUE THREAD

**Issue by omursahin** [omursahin/project_system#20]
Group: ForeignKey,
title: CharField 255 karakter, blank veya null olamaz
description: CharField 255 karakter, blank veya null olabilir
is_approved: BooleanField
status: CharField, Aşağıda belirtilen choice türünde olmalı. 

```
STATUS_CHOICES = (("A", "Approved"),
                      ("P", "Pending"),
                      ("D", "Draft"),
                      ("R", "Rejected"))
```

____
**Yetkilendirme Seviyesi**

Okuma: Authenticated
Yazma: Yalnızca Group Owner yazabilir.
___
**Not:** Daha sonra yalnızca Superuser tarafından is_approved alanı değiştirilebilir yapılacaktır. İlk versiyonda bu güvenlik kontrolüne gerek yok. Kodlarken dikkate almayabilirsiniz.

**Comment by OguzhanCnr** [comment]
Hocam yazma kısmını yalnızca Group Owner yazabilir şeklinde ayarlamaya çalıştık kontrol edebilir misiniz
