### ISSUE TITLE
Semester Course endpointi

### ISSUE THREAD

**Issue by omursahin** [omursahin/project_system#7]
semester: ForeignKey - Unique,
course: ForeignKey - Unique,
max_group_size: IntegerField

alanları olan bir model oluşturulmalıdır.
____
**Yetkilendirme Seviyesi**

Okuma: Authenticated
Yazma: Superuser

**Comment by OguzhanCnr** [comment]
semester = models.ForeignKey(Semester, on_delete=models.CASCADE, unique=True, null=False, blank=True)
 Hocam semester ForeignKey kısmını bu şekilde oluşturduk alttaki uyarıya göre mi düzeltelim yoksa bu şekilde mi bırakalım

semester_course.SemesterCourse.course: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
        HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.

**Comment by omursahin** [comment]
Uyarıya uygun düzenlemeleri yapsan daha iyi olur gibi duruyor.

**Comment by omursahin** [comment]
İki alanı eş zamanlı unique yapmak için şunu kullanabilirsiniz:

```
class MyModel(models.Model):
    field1 = models.CharField(max_length=50)
    field2 = models.CharField(max_length=50)
  
    class Meta:
      unique_together = ('field1', 'field2',)
```

**Comment by OguzhanCnr** [comment]
Hocam ForeignKey kullanıp aynı zamanda unique=True verdiğimiz için OneToOneField kullanmamız öneriliyormuş. ForeignKey kullanıp içerisinde unique belirtmeyip Meta sınıfında unique_together ile belirtince sorun çözüldü.

**Comment by OguzhanCnr** [comment]
![image](https://user-images.githubusercontent.com/89856152/232494850-215f4160-411b-458f-9d0d-71e93eeeea27.png)

Hocam semester eklerken django admin tarafında da bu şekilde hata alıyorum ancak postman kullanarak sıkıntısız ekleyebiliyorum
